### ISSUE TITLE
lsdsng loading fails

### ISSUE THREAD

**Issue by alexras** [alexras/lsmc#15]
Loading from an .lsdsng file is failing on OS X El Capitan. It appears that all .lsdsng files fail to load with the following stacktrace:
 
```
Error loading file: global name 'item' is not defined
Traceback (most recent call last):
  File "event_handlers.pyc", line 95, in ok_handler
  File "pylsdj/savfile.pyc", line 58, in __setitem__
NameError: global name 'item' is not defined
```

**Comment by alexras** [comment]
OK, luckily this looks like it's caused by a bug in pylsdj 2.3.2 that is fixed in pylsdj 2.3.3. So the next release build should include a fix for this.
